#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg JAVA_MAJOR_VERSION="8" \
    --build-arg JAVA_MINOR_REVISION="0.232" \
    --build-arg ESUM="E6A9D177933D45F9F1D38BF14E098B5A3FE4806D9EFB549066D1CFB4B03FE56F" \
    --build-arg ZULU_VERSION="8.42.0.23" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
