version: '3'

services:
  master:
    container_name: spark-master
    build:
      context: ./master
    volumes:
      - ./logs:/tmp/spark-events:rw
      - ./data:/volume:rw
    ports:
      - 18080:18080
      - 8080:8080
      - 8088:8088
      - 8042:8042
      - 8020:8020
      - 6060:6060
      - 4040:4040
      - 7077:7077
      - 9000:9000
      - 8030:8030
      - 8031:8031
      - 8032:8032
      - 8033:8033
      - 50070:50070
      - 19888:19888
      - 8888:8888
    expose:
      - 2122
      - 7077
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 6066
      - 8030
      - 8031
      - 8032
      - 8033
      - 8040
      - 8042
      - 8088
      - 8888
      - 9000
      - 8020
      - 50010
      - 50020
      - 50070
      - 50075
      - 50090
      - 19888
      - 49707
    environment:
      - MASTER=spark://master:7077
      - SPARK_PUBLIC_DNS=localhost
      - HADOOP_PREFIX=/usr/local/hadoop
      - YARN_CONF_DIR=/usr/local/hadoop/etc/hadoop
      - SPARK_HOME=/usr/local/spark
    hostname: master

  worker1:
    container_name: spark-worker1
    build:
      context: ./worker
    volumes:
      - ./logs:/tmp/spark-events:rw
      - ./data:/volume:rw
    ports:
      - 8081:8081
    expose:
      - 8081
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
    depends_on:
      - master
    links:
      - master
    environment:
      - MASTER=spark://master:7077
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_CORES=2
      - HADOOP_PREFIX=/usr/local/hadoop
      - YARN_CONF_DIR=/usr/local/hadoop/etc/hadoop
      - SPARK_HOME=/usr/local/spark
    hostname: worker1

  worker2:
    container_name: spark-worker2
    build:
      context: ./worker
    volumes:
      - ./logs:/tmp/spark-events:rw
      - ./data:/volume:rw
    ports:
      - 8082:8082
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8882
    depends_on:
      - master
    links:
      - master
    environment:
      - MASTER=spark://master:7077
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WORKER_PORT=8882
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_CORES=2
      - HADOOP_PREFIX=/usr/local/hadoop
      - YARN_CONF_DIR=/usr/local/hadoop/etc/hadoop
      - SPARK_HOME=/usr/local/spark
    hostname: worker2

