#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

BASE_TAG=$(basename ${DOCKERFILE_PATH} | cut -f 2 -d ".")

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg MAVEN_VERSION="3.6.3" \
    --build-arg MAVEN_SHA512SUM="c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0" \
    --build-arg BASE_TAG="${BASE_TAG}" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
